[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/delete-your-data.html"
  to = "/delete-your-data"
  status = 301
  force = true